import streamlit as st
def page_3():
    st.title("Sinopsis")
    st.write("Halaman ini akan memberitahukan jalan cerita anime")
    st.write("1. Kimetsu no Yaiba")
    st.write("Anime Demon Slayer: Kimetsu no Yaiba – To the Hashira Training akan menampilkan kompilasi episode 11 berjudul “A Connected Bond: Daybreak and First Light” dari arc Swordsmith Village sebagaimana dikutip dari Deadline. Film ini akan menampilkan akhir dari pertarungan sengit antara Tanjiro dan Empat Atas, Hantengu, dan kemenangan Nezuko atas matahari. Sinopsis Film Demon Slayer: Kimetsu No Yaiba - To the Hashira Training. Baca selengkapnya di artikel Sinopsis Film Demon Slayer To the Hashira Training, https://tirto.id/gVNy")
    st.write("2. Attack on Titan")
    st.write("Attack on Titan merupakan sebuah anime yang diadaptasi dari manga populer karangan Hajime Isayama. Manga tersebut diadaptasi menjadi sebuah seri anime yang diproduksi oleh Wit Studio dan MAPPA. Ceritanya sendiri mengisahkan tentang umat manusia yang harus bersembunyi di sebuah wilayah dengan dikelilingi tiga lapis tembok besar agar tidak dimakan oleh raksasa.")
    st.write("3. Jujutsu Kaisen")
    st.write("Jujutsu Kaisen 0: The Movie merupakan film bergenre fantasi animasi produksi Jepang tahun 2021, yang dibuat berdasarkan serial manga Jujutsu Kaisen 0, sebuah prekuel dari seri manga Jujutsu Kaisen, di mana keduanya dibuat oleh Gege Akutami. Mengisahkan tentang Yuta Okkotsu dihantui oleh roh teman masa kecilnya Rika, yang meninggal dalam kecelakaan lalu lintas. Semangatnya tidak lagi muncul sebagai gadis manis yang disebut kekasihnya. Sebaliknya, rohnya telah dikutuk dan dia bermanifestasi sebagai entitas mengerikan yang melindunginya dari keinginannya. Baca selengkapnya di artikel Jujutsu Kaisen 0 The Movie: Sinopsis & Jadwal Tayang di Indonesia, https://tirto.id/gpSw.")
    st.write("4. Black Clover")
    st.write("Black Clover: Sword of the Wizard King menceritakan rintangan terbaru yang harus dihadapi Asta dan rival abadinya, Yuno, dalam upaya mereka untuk menjadi Kaisar Sihir. Kali ini, Asta, Yuno, serta rekan-rekan Ksatria Sihirnya harus melawan Kaisar Sihir ke-27 di Clover Kingdom, yakni Conrad Leto, yang menjabat sebelum Julius Novachrono. Conrad dulunya adalah Kaisar yang begitu dihormati dan dicintai rakyat, sampai akhirnya dia memberontak lalu disegel. Kini, Conrad berhasil bebas dan berupaya untuk mengambil alih kerajaan.")